### ISSUE TITLE
Want helping setting up Node 

### ISSUE THREAD

**Issue by kody435** [weavedb/weavedb#269]
## Want some help following this part, please reach out here or in discord Will_Buyers#0539

![Screenshot 2023-01-25 at 4 10 11 PM](https://user-images.githubusercontent.com/50862704/214542554-15c95b6f-c30b-4d4a-98c9-f8e6a6252e81.png)

**Comment by ocrybit** [comment]
This is not related to development. Please ask for help in a Discord channel with a specific question.
