### ISSUE TITLE
deployACL script arguments mismatch

### ISSUE THREAD

**Issue by drumfeet** [weavedb/weavedb#312]
Instructions on the [tutorial](https://docs.weavedb.dev/docs/examples/lit-protocol#deploy-acl-contract-on-evm) does not have the `NFT_ADDRESS` environment variable.
Command line argument is missing from the script.
Not sure wether to use env variable or command line argument.

<img width="997" alt="image" src="https://user-images.githubusercontent.com/4261233/215960158-3c3097c1-cc64-42a2-aee0-5b56d8774876.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/4261233/215960318-f865b814-c49d-429e-a590-236b245470c5.png">

**Comment by ocrybit** [comment]
`npx hardhat run` cannot have command-line arguments, so there should be `NFT_ADDRESS` in the `.env` file.
I have updated the tutorial.
https://docs.weavedb.dev/docs/examples/lit-protocol#deploy-acl-contract-on-evm
