### ISSUE TITLE
Messages from a previously connected wallet are displayed

### ISSUE THREAD

**Issue by drumfeet** [weavedb/weavedb#330]
Issue can be replicated on the demo app [https://relayer-one.vercel.app/lit-protocol](https://relayer-one.vercel.app/lit-protocol)

I used 2 wallets with different tokenIDs per wallet.
After disconnecting a wallet with lit protocol, I switched and connect another wallet from metamask.
The messages from the previous wallet are being displayed then quickly disappears before the messages from the new wallet are shown.
I tried to set nocache to true from get query but still the same.

**Comment by ocrybit** [comment]
I slightly updated the msg display logic, so it should be ok now. You can check the diff in the linked commit or this tutorial.
https://docs.weavedb.dev/docs/examples/lit-protocol#set-up-reactive-effect
