### ISSUE TITLE
IDEA: move some code from grpc-node/node-server to grpc-node/node-server/src 

### ISSUE THREAD

**Issue by 0xkaz** [weavedb/weavedb#390]
I feel grpc-node/node-server is messy. It's just small idea to organize the directory.

**Comment by ocrybit** [comment]
Thanks for the suggestion. I was going to abstract out the codebase into an npm package but pre-organized it based on your suggestion. https://github.com/weavedb/weavedb/commit/14f396f4d1a7bc7f68f1a462467d6e7992aae3f7

I kept `server.js` in the root directory and didn't make changes that cause path modifications in some config settings.
