### ISSUE TITLE
IDEA/Question: Shouldn't the collection name be alphanumeric only?

### ISSUE THREAD

**Issue by 0xkaz** [weavedb/weavedb#401]
![image](https://user-images.githubusercontent.com/87490841/217765385-7d6a8edd-24a5-4094-bf85-a138e96cb0eb.png)

**Comment by ocrybit** [comment]
No, it can be any valid UTF-8 characters except for `/`.

WeaveDB follows the Firestore name restrictions.
https://firebase.google.com/docs/firestore/quotas#collections_documents_and_fields
