### ISSUE TITLE
Error: Cannot find module '../sdk-web'

### ISSUE THREAD

**Issue by jorgebenzeno** [weavedb/weavedb#568]
//const SDK = require("weavedb-sdk")
const SDK = require("../sdk-web")
class SDKNODE extends SDK {
  constructor(param) {
    const { LmdbCache } = require("warp-contracts-lmdb")
    const { createClient } = require("redis")
    const {
      WarpSubscriptionPlugin,
    } = require("./warp-contracts-plugin-subscription")
    super({
      ...{ LmdbCache, createClient, WarpSubscriptionPlugin },
      ...param,
    })
  }
}

module.exports = SDKNODE

**Comment by ocrybit** [comment]
This has been resolved by #567.

**Comment by ocrybit** [comment]
This has been resolved by #567.
