### ISSUE TITLE
I think there is an issue with the 'weavedb-sdk' package

### ISSUE THREAD

**Issue by mendsalbert** [weavedb/weavedb#584]
<img width="729" alt="Screenshot 2023-05-07 at 6 59 41 PM" src="https://user-images.githubusercontent.com/40429398/236697371-be44eb2d-0be5-4cee-935c-dab0baea7580.png">

I have been facing this error for the past 3 days.

below is more context of what the code is trying to. I am trying to implement the todo example on the weavedb docs page.

this is the code causing that.
`const contractTxId = "0P-YuG46ghkoxUTiZ_rkRsnqxxlTLVpzYVLd5FXwA80";
  const setupWeaveDB = async () => {
    window.Buffer = Buffer;
    db = new SDK({
      contractTxId,
    });
    await db.initializeWithoutWallet();
    setInitDB(true);
  };`

@drumfeet @ocrybit @kody435 @ahmadmardeni1 @0xkaz 
 
 Thanks in advance.

**Comment by kody435** [comment]
Can you send the particular GitHub repo's direct link to the file, I can check  and tell you more about it.

**Comment by mendsalbert** [comment]
Thanks for your prompt response.

https://github.com/mendsalbert/vidispark/blob/main/Documents/vidispark/pages/26-upload-artwork.js

**Comment by kody435** [comment]
Surely there is an issue with how you define the **db** variable. This could be the hint I could give you from the code you provided.

**Comment by mendsalbert** [comment]
The code was copied from weavedb docs. Below is the link to the docs
https://docs.weavedb.dev/docs/examples/todos-console#the-complete-code

**Comment by kody435** [comment]
You guessed right, there is some kinda problem with the _weavedb-sdk_**** package.

**Comment by kody435** [comment]
You guessed right, there is some kinda problem with the _weavedb-sdk_**** package. @ocrybit Can you help us here.

**Comment by ahmadmardeni1** [comment]
Hi! Can you revert to [V0.26.10](https://www.npmjs.com/package/weavedb-sdk/v/0.26.10)? Warp has made some changes that affected the last few versions, we are working on a stable Beta release to solve this issue in the next few days. @mendsalbert 

Thanks for helping! @kody435

**Comment by drumfeet** [comment]
@mendsalbert 

I recommend you clone this branch instead https://github.com/weavedb/weavedb/tree/v0.25
Deploy a new contract by executing
`yarn`
`node scripts/generate-wallet.js mainnet`
`yarn deploy`

You can run the todos example from the repo by:


- open /weavedb/examples/todos/pages/index.js 
- replace `WEAVEDB_CONTRACT_TX_ID` with the contractTxId returned when deploying the WeaveDB contract.
- open /weavedb/examples/todos/package.json
- replace "weavedb-sdk": "^0.7.32" to "weavedb-sdk": "^0.26.10"
- `cd examples/todos`
- `yarn`
- `yarn dev`

**Comment by mendsalbert** [comment]
Thank you all for your assistance it’s working now but why do i have sign any action on the database using a web3 provider like metamask?Examples adding or mutating record on the database show a metamask pop up?Is this a default beginning or it can be changed?Sent from my iPhoneOn 10 May 2023, at 2:56 AM, drumfeet ***@***.***> wrote:﻿
@mendsalbert
I recommend you clone this branch instead https://github.com/weavedb/weavedb/tree/v0.25
Deploy a new contract by executing
yarn
node scripts/generate-wallet.js mainnet
yarn deploy
You can run the todos example from the repo by:

open /weavedb/examples/todos/pages/index.js
replace WEAVEDB_CONTRACT_TX_ID with the contractTxId returned when deploying the WeaveDB contract.
open /weavedb/examples/todos/package.json
replace "weavedb-sdk": "^0.7.32" to "weavedb-sdk": "^0.26.10"
cd examples/todos
yarn
yarn dev

**Comment by ahmadmardeni1** [comment]
Hey @mendsalbert if you are using the console, it only requires you to sign the first time, and using the SDK, no need to sign.

**Comment by mendsalbert** [comment]
So meaning a user is supposed to sign every single action like add , edit and delete at the client???

**Comment by ahmadmardeni1** [comment]
No, the opposite, users don't need to sing anything. @mendsalbert 

For more info on how WeaveDB works:
- https://weavedb.mirror.xyz/E4VmonwIP2hV3W3wIum3oFz4giAPzM2E_DeSRLQelL0
- https://weavedb.mirror.xyz/IgIYseuHWflf29xPnmlcegbRdYSJWUd28SjAbyVLEno

**Comment by mendsalbert** [comment]
￼

Anytime a user logs in this particular error appears. I have tried web3modal , ethers, web3 and wagmi providers but still seeing this error.

I suspect it is coming from


if (isNil(identity)) {
        ({ tx, identity, err } = await db.createTempAddress(wallet_address));

        const linked = await db.getAddressLink(identity.address);
        console.log(linked);
        if (isNil(linked)) {
          alert("something went wrong");
          return;
        }
      } else {
        await lf.setItem("temp_address:current", wallet_address);
        setUser({
          wallet: wallet_address,
          privateKey: identity.privateKey,
        });
        return;
      }


This block of code inside the login function

**Comment by drumfeet** [comment]
@mendsalbert 
I'm not entirely sure about the error. It works fine on my end deploying a specific version of the sdk
Are you running the todo example from the repo?
can you share the `contractTxId` ? 
I'd like to check which version of weavedb-sdk you've deployed

**Comment by mendsalbert** [comment]
j5s68rGOvaIvhaGFsvK2R57iMphr7uFrqZbvqbFHc4w

**Comment by mendsalbert** [comment]
I was able to fix that but seems I'm getting a new error  🥲
<img width="631" alt="Screenshot 2023-05-10 at 11 06 42 AM" src="https://github.com/weavedb/weavedb/assets/40429398/e028be44-eba5-46a2-bae0-44fa640e780b">

**Comment by drumfeet** [comment]
@mendsalbert I've checked the contract and you don't have a collection created yet.

**Comment by mendsalbert** [comment]
Whew, I'm really struggling with getting this task done. I'm working with the contractTxId 0P-YuG46ghkoxUTiZ_rkRsnqxxlTLVpzYVLd5FXwA80, and I've set up all the necessary schemas, but whenever I try to add a task, I keep getting an error message saying 'operation not allowed'. I'm not sure what's going wrong, and it's really frustrating. Any help or advice would be greatly appreciated!

**Comment by ahmadmardeni1** [comment]
@mendsalbert There are two possible issues here:
1. You didn’t create a collection so you can’t add a task to a non-existing collection and it seems to be the issue:
https://sonar.warp.cc/?#/app/contract/j5s68rGOvaIvhaGFsvK2R57iMphr7uFrqZbvqbFHc4w

2. You are trying to write to your database from a wallet that does not have access:
https://docs.weavedb.dev/docs/sdk/rules

If this is your first time using WeaveDB/NoSQL database, we recommend going through this tutorial:
https://weavedb.dev/docs/quick-start

**Comment by ahmadmardeni1** [comment]
![Uploading 2E3CA3A1-F66C-4FCC-8E07-CF4A11F6B3ED.png…]()

Oh as I thought, your transactions (setting up schema and access control ruels) didn’t go through because of the SDK changes. You can redo it now with the 0.26.10

Sorry for the trouble! The reason why the latest SDK version does not work that Warp did some changes and the SDK is not compatible with them, we are working on a stable release this month.

**Comment by ahmadmardeni1** [comment]
Oh as I thought, your transactions (setting up schema and access control ruels) didn’t go through because of the SDK changes. You can redo it now with the 0.26.10

Sorry for the trouble! The reason why the latest SDK version does not work that Warp did some changes and the SDK is not compatible with them, we are working on a stable release this month.

![0431CB31-7F27-426B-A6A7-BCBCC9AE4F32](https://github.com/weavedb/weavedb/assets/63211822/a7a843bb-688b-4d7a-8fcf-60ee28056c5c)

**Comment by mendsalbert** [comment]
<img width="1411" alt="Screenshot 2023-05-10 at 12 23 11 PM" src="https://github.com/weavedb/weavedb/assets/40429398/6dc9b111-e21b-42ac-88d2-c78d6a06e1c1">


what does "The wrong signature" mean? I have logged and all

**Comment by ahmadmardeni1** [comment]
Are you using this Arweave wallet PgL--hkNo_x5HijC2EKyIkxAEwik6DxpqmSg5CRiMBE on the console?

**Comment by ahmadmardeni1** [comment]
Then you have to use the same owner wallet or write an access control rule to give access to the second wallet:
https://docs.weavedb.dev/docs/sdk/rules

or you can deploy a new one using the console and follow this tutorial:
https://docs.weavedb.dev/docs/quick-start

**Comment by ocrybit** [comment]
```
The initialization error should have been fixed by #567.

**Comment by mendsalbert** [comment]
Alright , thanks everything works perfectly now
