### ISSUE TITLE
How to delete a collection?

### ISSUE THREAD

**Issue by rts-gordon** [weavedb/weavedb#711]
Hi there,

   Thanks for WeaveDB production, it is a useful infra in web3.
  
   How to delete a collection, I tried delete collection_name, remove collection_name, drop collection_name, they all don't work.

   Thank you.

**Comment by drumfeet** [comment]
You cannot delete a collection. Create a new collection instead.
Deleting an entire collection can be a dangerous operation.
Each document in a collection is typically owned by multiple users.
If a user deletes an entire collection, they are effectively deleting the data of all the other users who own documents in that collection.
Ignoring data ownership is equivalent to a centralized system.
