### ISSUE TITLE
Can't deploy testnet wallet

### ISSUE THREAD

**Issue by fco-fbatch** [weavedb/weavedb#93]
I am following the official docs of [Contract Deployment](https://weavedb.asteroid.ac/docs/development/deploy).

As the docs suggest I am executing the below commands,
```
node scripts/generate-wallet.js testnet
node scripts/add-funds.js testnet
yarn deploy-testnet
```

Getting the following error after executing the `yarn deploy-testnet` command.

```
yarn run v1.22.19

error Command "deploy-testnet" not found.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ocrybit** [comment]
oh, we have removed the testnet deployment since the testnet is not so stable. And it seems Redstone (the testnet maintainer) wants to get rid of it.
For now you can test on the mainnet for free, but we will develop a better local test environment soon. #95
